invadersVelocity : 1
invadersMaxVelocity : 5
invadersVelocityStep : 1
shot : 200
invadersShot : 900
bonusInvaders : 15000
bonusInvaderPosAbs : 0
bonusInvaderPosOrd : 0
playerPosAbs : 0
playerPosOrd : 50
lives : 3
score : 0
bestScore : 0
scoreForMissileDestruction : 50
scoreStep : 100
scoreStepBonusInvaders : 500
torpedoVelocity : 20
wave : 1
